ws_visualizer.go:
	go build ws_visualizer.go

install: ws_visualizer.go
	install ws_visualizer /usr/bin/
	install launchlemon.sh /usr/bin/launchlemon
	install lemonconfig.sh /usr/bin/lemonconfig

clean:
	rm -f ws_visualizer
